baseurl = "http://thisismk.github.io/booyah"
title = "Start Bootstrap Clean Blog"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en"
copyright = "Code released under the Apache 2.0 license.."

[author]
    name = "Benoît Benedetti"
[params]
  DateForm = "Mon, Jan 2, 2006"
  Author = "Benoît Benedetti"
  email = "benoit.benedetti@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/mktantum"
[[params.social]]
    title = "github"
    url = "https://github.com/thisismk"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/mktantum"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180